- name: Deploy waiting-time-backend
  hosts: main
  remote_user: ihar
  vars:
    deployment_dir: /home/ihar/deployments/waiting-time-backend

  tasks:
    - name: Install Docker to Python
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - docker-compose

    - name: Copy configuration files
      copy:
        src: "{{ item }}"
        dest: "{{ deployment_dir }}"
        mode: 0644
      with_items:
        - docker-compose.yml
        - nginx.conf
        - env.production

    - name: Pull updated Docker images and restart containers
      community.docker.docker_compose:
        project_src: "{{ deployment_dir }}"
        project_name: waiting-time-backend
        env_file: "{{ deployment_dir }}/env.production"
        environment:
          DATABASE_URL: "{{ DATABASE_URL }}"
          POSTGRES_DB: "{{ POSTGRES_DB }}"
          POSTGRES_USER: "{{ POSTGRES_USER }}"
          POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
        pull: yes
        build: no
        remove_orphans: yes
        remove_volumes: yes
        state: present
        restarted: yes
