services:

  web:
    image: nokal/waiting-time-backend
    build: .
    volumes:
      - ./assets:/srv/webapp/assets
    env_file:
      - .env
    restart: always
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON_URL: http://${WEBAPP_HOST}/swagger.json
    depends_on:
      - web
    restart: always

  nginx:
    image: nginx
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    env_file:
      - .env
    depends_on:
      - web
      - swagger

  db:
    image: postgres:16.0
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always

  database-api:
    build: ./database-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    volumes:
      - /root/pix/waiting-time-backend/database-api:/app/logs
