services:

  web:
    image: nokal/waiting-time-backend
    build: .
    volumes:
      - ./assets:/srv/webapp/assets
    environment:
      WEBAPP_HOST: ${WEBAPP_HOST}
    restart: always

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON_URL: http://${WEBAPP_HOST}/swagger.json
    depends_on:
      - web
    restart: always

  nginx:
    image: nginx
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    environment:
      NGINX_HOST: ${NGINX_HOST}
    depends_on:
      - web
      - swagger