services:

  web:
    image: nokal/waiting-time-backend
    build: .
    volumes:
      - ./assets:/srv/webapp/assets
    environment:
      WEBAPP_HOST: ${WEBAPP_HOST}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON_URL: http://${WEBAPP_HOST}/swagger.json
    depends_on:
      - web
    restart: always

  nginx:
    image: nginx
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    environment:
      NGINX_HOST: ${NGINX_HOST}
    depends_on:
      - web
      - swagger

  db:
    image: postgres:16.0
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always

  database-api:
    build: ./database-api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    restart: always
