services:

  web:
    build: .
    volumes:
      - ./assets:/srv/webapp/assets
    restart: always

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON_URL: http://${WEBAPP_HOST}/swagger.json
    depends_on:
      - web
    restart: always

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - web
      - swagger