name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - Dockerfile
      - ./**/*.go
      - ./.github/workflows/build.yaml
  pull_request:
    branches:
      - main
      - Dockerfile
      - ./**/*.go
      - ./.github/workflows/build.yaml

env:
  MODULE_NAME: github.com/AutomatedProcessImprovement/waiting-time-backend
  DOCKERHUB_USERNAME: nokal
  DOCKERHUB_REPO: nokal/waiting-time-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'

      - name: Install dependencies
        run: go get ${{ env.MODULE_NAME }}

      # Testing

      - name: Run tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

      - name: Build binaries
        run: bash build_app.bash

      # Build a Docker image

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: github.ref != 'refs/heads/main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: github.ref != 'refs/heads/main'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.ref != 'refs/heads/main'
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        if: github.ref != 'refs/heads/main'
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:latest, ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64

      # Artifacts

      - uses: actions/upload-artifact@v3
        if: github.ref != 'refs/heads/main'
        with:
          name: darwin-amd64.tar.gz
          path: build/darwin-amd64.tar.gz

      - uses: actions/upload-artifact@v3
        if: github.ref != 'refs/heads/main'
        with:
          name: darwin-arm64.tar.gz
          path: build/darwin-arm64.tar.gz

      - uses: actions/upload-artifact@v3
        if: github.ref != 'refs/heads/main'
        with:
          name: linux-amd64.tar.gz
          path: build/linux-amd64.tar.gz

      - uses: actions/upload-artifact@v3
        if: github.ref != 'refs/heads/main'
        with:
          name: windows-amd64.zip
          path: build/windows-amd64.zip
