name: Deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Ansible
        run: |
          sudo rm -rf /usr/lib/python3/dist-packages/OpenSSL
          sudo apt-get update
          sudo apt-get install --only-upgrade openssl
          sudo apt-get install -y python3-pip
          pip3 install -U pip ansible docker docker-compose pyyaml
          ansible --version
          docker --version

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          name: "id_rsa-ga"
          known_hosts: "${{ secrets.KNOWN_HOSTS }}"

      - name: Deploy with Ansible
        run: |
          ansible-playbook -i hosts.yaml --private-key ~/.ssh/id_rsa-ga deploy.yaml

