name: Deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install --only-upgrade openssl
          sudo apt-get install -y python3-pip
          pip3 install -U pip ansible pyyaml
          ansible --version
          docker --version

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          name: "id_rsa-ga"
          known_hosts: "${{ secrets.KNOWN_HOSTS }}"

      - name: Deploy with Ansible
        run: |
          ansible-playbook -i hosts.yaml --private-key ~/.ssh/id_rsa-ga deploy.yaml \
          -e "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
          -e "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" \
          -e "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" \
          -e "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
          -e "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
        continue-on-error: true

      - name: Collect logs if deployment fails
        if: failure()
        run: |
          echo "Deployment failed, attempting to gather all container logs..."
          ansible all -i hosts.yaml --private-key ~/.ssh/id_rsa-ga -m shell -a 'docker ps -aq | xargs -r docker logs' # Collects logs from all containers
          ansible all -i hosts.yaml --private-key ~/.ssh/id_rsa-ga -m shell -a 'journalctl -u docker.service --no-pager'
