name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MODULE_NAME: github.com/AutomatedProcessImprovement/waiting-time-backend
  DOCKERHUB_USERNAME: nokal
  DOCKERHUB_REPO: nokal/waiting-time-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'

      - name: Install dependencies
        run: go get ${{ env.MODULE_NAME }}

      # Testing

      - name: Run tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

      - name: Build binaries
        run: bash build_app.bash

      # Build a Docker image

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:latest, ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64

      # Artifacts

      - uses: actions/upload-artifact@v3
        with:
          name: darwin-amd64.tar.gz
          path: build/darwin-amd64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: darwin-arm64.tar.gz
          path: build/darwin-arm64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: linux-amd64.tar.gz
          path: build/linux-amd64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: windows-amd64.zip
          path: build/windows-amd64.zip

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip3 install ansible
          ansible --version

      - name: Deploy waiting-time-backend
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yaml
          inventory: hosts.yaml
          key: ${{ secrets.GITHUB_ACTIONS_USER_PRIVATE_KEY }}

