name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: nokal
  DOCKERHUB_REPO: nokal/waiting-time-backend
  MODULE_NAME: github.com/AutomatedProcessImprovement/waiting-time-backend
  BIN_NAME: waiting-time-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'

      - name: Install dependencies
        run: go get $MODULE_NAME

      - name: Build binaries
        run: bash build.bash

      - uses: actions/upload-artifact@v3
        with:
          name: darwin-amd64.tar.gz
          path: build/darwin-amd64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: darwin-arm64.tar.gz
          path: build/darwin-arm64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: linux-amd64.tar.gz
          path: build/linux-amd64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: windows-amd64.tar.gz
          path: build/windows-amd64.tar.gz
